## Docker Compose for development
version: "3"
services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: defaultdb
    ports:
      - "5432:5432"
    volumes:
      - nemesis-db:/var/lib/postgresql/data

volumes:
  nemesis-db:
